### ISSUE TITLE
A more detailed example?

### ISSUE THREAD

**Issue by cmyr** [pirogoeth/unix-named-pipe#1]
I've been playing around a bit with unix pipes in Rust and found this, which looks like an interesting resource; but I'd be really curious to see a simple example in the docs that shows how I could use this to communicate between two processes.

In particular, I've been trying to build a toy client/server where the client starts the server and then enters a read loop on a pipe, which the server periodically writes to, but I haven't had much luck.

**Comment by pirogoeth** [comment]
@cmyr Sure, I'll see what I can work up :)

**Comment by cmyr** [comment]
@pirogoeth thanks!

**Comment by pirogoeth** [comment]
Hey @cmyr, you mind checking out this PR and seeing if it fits your needs? https://glow.dev.maio.me/sjohnson/unix-named-pipe/merge_requests/2/diffs

**Comment by cmyr** [comment]
Very cool, would have to clone and play around a bit but that looks great.

I thought the interrupt handling was maybe overkill, and you could just write a little `FileGuard` struct that removed the pipe in `drop`, but I guess the signal kills the process without drop being called?

I've got _something_ working now, with mio, but I couldn't get anything working reliably without it; my reads would consistently return `Ok(0)`. I'm thought maybe I was supposed to close the fd to flush, but that wasn't working either?

In any case, thanks for taking the time out of your weekend!

**Comment by pirogoeth** [comment]
@cmyr The interrupt handling is _very possibly_ overkill, so I'll certainly have to look in to the `drop` behaviour is when a Rust program is keyboard interrupted.

Since FIFOs are just buffers like pipes, doing a `flush` or `close` to flush isn't going to do what you'd expect. `flush` _should_ just be a no-op in that case, and `close` would actually cause `io::ErrorKind::BrokenPipe` on the write side of the pipe if the read side is closed, and the read side of the pipe would "spin" forever if the write side was closed.   

No worries at all, this is what I enjoy doing! Glad I was able to help a bit. 😄

**Comment by pirogoeth** [comment]
Hey @cmyr, I looked into `drop` behaviour and it does not look like drops will run when a program is keyboard interrupted. This is what I ended up doing: https://gist.github.com/pirogoeth/75672dbd4c2936b1cf836b90a68159b8

What _does_ work (as expected, I'd suppose) is using the `ctrlc` handler as a loop break flag, so then `main` finishes and all drops execute.

This was a lot of fun to look in to, thanks! 😄

**Comment by cmyr** [comment]
Interesting, good to know.

I'm starting to think that one of my earlier problems might be that I'm playing around on macOS, where fifo behaviour might be a bit different?

**Comment by cmyr** [comment]
One other thing I'm curious about is how this would handle variable sized messages? I noticed this was one of the major differences between your test cases and what I was trying yesterday (your use of `read_exact`, and here that you're using  a small buffer and reading fixed-size messages)

**Comment by pirogoeth** [comment]
I am also on macOS and things (so far) have worked fine. I _think_ the macOS FIFO subsystem is POSIX compliant, so there _shouldn't_ be any issues there.

Variable-sized messages should certainly be doable with some care. I'll see if I can work out a good example for that as well. :)
As long as the individual messages are "well-delimited", sending variable-sized payloads shouldn't be an issue.

**Comment by cmyr** [comment]
Okay, my thinking about macOS came from finding various sources that mentioned behaviour being different between different versions of linux; I guess POSIX leaves certain behaviour unspecified (like opening for write without an existing reader)[1].

fwiw, my use case would be reading newline delimited JSON.

1 https://stackoverflow.com/questions/52015639/linux-named-fifo-non-blocking-read-select-returns-bogus-read-fds

**Comment by pirogoeth** [comment]
Okay, I see what you're saying. In our case on macOS, continuing to read from the FIFO after the client closes works, but that might not work on Linux. Although, since there's no ctrlc handler in the client, the write end of the fd might not be getting closed cleanly since drops are not happening.

Newline-delimited JSON seems like it will be a pretty common use case, so I'll add an example or integration tests around that.

**Comment by pirogoeth** [comment]
Hey @cmyr, sorry for the delay! Do the new examples [here](https://glow.dev.maio.me/sjohnson/unix-named-pipe/merge_requests/3/diffs) fit your use-case?

**Comment by cmyr** [comment]
@pirogoeth no apologies necessary! 😉 These new examples are great, but my use-case keeps expanding to keep pace. My latest frustration has been trying to use a pair of pipes for bidirectional communication between a parent and child process; _this_ I haven't been able to get to work. But maybe instead of expecting you to spend your evening hacking up demos for me I could at least push it somewhere and you could take a peek?

**Comment by pirogoeth** [comment]
@cmyr that works for me!

Although, since you need bidirectional communication, you might need to use Unix domain sockets instead. They support bidirectional communication with the `SOCK_STREAM` option.

**Comment by cmyr** [comment]
Yea, I've been curious to compare performance between unix sockets and named pipes, so I was hoping to get them both working? In any case this is a speculative evenings and weekends thing for me, but I'll try and hack together a minimal example of my current blockage, probably tomorrow.

**Comment by pirogoeth** [comment]
I'm very curious about the performance as well, so please let me know how it turns out! Looking forward to seeing your examples :)

**Comment by cmyr** [comment]
Sounds good, be in touch. 😎

**Comment by cmyr** [comment]
Okay, played around a bit now and I have something working; basically it seems like reads would spin forever if I was just using `file::read`, but if I add a `BufReader` and use `read_until` with some delimiter everything is fine.

I'll do some more digging, but the basic conclusion is that I probably just don't know how the `read()` system call works. 😄

**Comment by pirogoeth** [comment]
@cmyr Awesome! So `BufReader` is the secret sauce for messages with delimiters :)

If you just did `File::open("path/to/file").unwrap().read(&mut buf)`, that will not work properly as named pipes need to be opened for nonblocking IO.

**Comment by cmyr** [comment]
@pirogoeth but even if I open the pipe with `O_NOBLOCK`, all of my reads calls were returning `Ok(0)`. In any case, will investigate a bit more. 😕

**Comment by pirogoeth** [comment]
Could you share some code? Maybe I can help better that way :)

**Comment by cmyr** [comment]
Okay, here's an example:

https://github.com/cmyr/nextgen2/blob/master/examples/bidirectional.rs

running this with `cargo run --example=bidirectional spawn` will start the client and server processes, and they will communicate over a pair of named pipes, using a `BufReader`.

If I replace the BufReader with just direct calls to `read`, they will always return `Ok(0)`.

**Comment by pirogoeth** [comment]
Hey, I've taken a cursory glance and started playing a bit, but I'll dig deeper this evening after work :)

**Comment by pirogoeth** [comment]
Okay, I dug into the `sys::fs` code to see what happens in `std::fs::File::read`. On Unix, it's a straight `libc::read` call, which uses `cmp::min(buf.len(), max_len())`, so maybe it would end up reading 0 bytes from the underlying fd since the `Vec` is empty?

**Comment by cmyr** [comment]
Innnnteresting. That does sound suspicious. I was also in that file today, but didn't notice. I'll play around a bit and maybe open an issue with the rust docs, that feels like a big enough gotcha that it should be written down somewhere.

**Comment by pirogoeth** [comment]
Fwiw, here's what I found: https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/fd.rs#L60

**Comment by cmyr** [comment]
oh wait, it _is_ in the docs:

>If the return value of this method is Ok(n), then it must be guaranteed that 0 <= n <= buf.len(). A nonzero n value indicates that the buffer buf has been filled in with n bytes of data from this source. If n is 0, then it can indicate one of two scenarios:

> 1. This reader has reached its "end of file" and will likely no longer be able to produce bytes. Note that this does not mean that the reader will always no longer be able to produce bytes.
> **2. The buffer specified was 0 bytes in length.**

oops. Well, thanks again for all your help!

**Comment by pirogoeth** [comment]
Ah! Glad I could help! Feel free to hit me up if you've got more questions in the future! 😄
